config/routes.rb
Rails.application.routes.draw do

  resources :videos
  devise_for :users 
  root :to => "static_pages#home"
  resources :categories

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :videos

  validates :title, :image, presence: true
  validates :title, :uniqueness => {:case_sensitive => false}
  validates_each :title do |record, attr, value|
    record.errors.add(attr, 'must start with upper case') if value =~ /\A[[:lower:]]/
  end

  mount_uploader :image, ImageUploader
end

app/models/email.rb
class Email < ActiveRecord::Base
	belongs_to :user, :category
end

app/models/follower.rb
class Follower < ActiveRecord::Base
	validates :user_id, :follow_user_id, presence: true 
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :category

  validates :title, :video_link, :thumbnail, :category_id, :video_link, presence: true
  validates :title, :uniqueness => {:case_sensitive => false}

  mount_uploader :thumbnail, ThumbnailUploader
  
  mount_uploader :video_link, VideoLinkUploader 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
      protected
        def configure_permitted_parameters
          devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:first_name, :last_name, :email, :password, :current_password) }
          devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:first_name, :last_name, :email, :password, :current_password) }
        end 
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end
  
  def new
    @category = Category.new
  end

  def create
    @category = Category.new permitted_params
    if @category.save
      flash! :success, :locals => {:title => @category.title}
      redirect_to categories_path
    else
      flash!(:error)
      render :new
    end
  end

  def edit
    @category = Category.find params[:id]
  end

  def update
    @category = Category.find params[:id]
    if @category.update permitted_params
      flash!(:success)
      redirect_to categories_path
    else
      flash!(:error)
      render :edit
    end
  end

  def show
    
  end

  def destroy
    @category = Category.find params[:id]
    if @category.destroy
      flash! :warning, :locals => {:title => @category.title}
      redirect_to categories_path
    else
      flash!(:error)
      redirect_to categories_path
    end
  end 

  private
    def permitted_params
      params.require(:category).permit(:title, :image)
    end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
	before_action :authenticate_user!
  
  def show
  end

  def index
    @conversations = @mailbox.inbox.paginate(page: params[:page], per_page: 10)
  end

  private

  def get_mailbox
    @mailbox ||= current_user.mailbox
  end

  def get_conversation
    @conversation ||= @mailbox.conversations.find(params[:id])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def index
    @videos = Video.all
    @categories = Category.all
  end

  def new
    @video = Video.new
  end

  def create
    @video = Video.new video_params

    if @video.save
      flash! :success, :locals => {:title => @video.title}
      redirect_to @video
    else
      flash!(:error)
      render :new 
    end
  end

  def show
    @video = Video.find(params[:id])
  end

  def list
    @video = Video.all
  end

  def edit
    @video = Video.find(params[:id])
  end

  def update
    @video = Video.find(params[:id])

    if @video.update update.params
      flash!(:success)
      redirect_to videos_path
    else
      flash!(:error)
      render :edit
    end
  end

  def destroy
    @video = Video.find(params[:id])

    if @video.destroy
      flash! :warning, :locals => {:title => @video.title}
      redirect_to videos_path
    else
      flash!(:error)
      redirect_to videos_path
    end
  end

  private
  def video_params
    params.require(:video).permit(:title, :description, :thumbnail, :category_id, :video_link)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def page_header(text)
  	content_for(:page_header) { text.to_s }
	end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/categories/_form.haml
- if @category.errors.any?
  %h3
    = pluralize(@category.errors.count, "error")
    prohibited this category from being saved:
  %ul
    - @category.errors.full_messages.each do |msg|
      %li= msg

= form_for @category, :html => {:multipart => true} do |f|
  %p Title:
  = f.text_field :title, placeholder: "Title"
  %p Image:
  = f.file_field :image, name: "category[image]"
  %p
  = f.submit

app/views/categories/edit.haml
%h1 Edit Category
 
= render 'form'

app/views/categories/index.haml
%h1 Categories

#flash_messages= flash_messages(:close, :fade)

= link_to "Add New Categories", new_category_path

%br 
%table
  %thead
    %th Image
    %th Title
    %th Actions
  %tbody
    - @categories.each do |category|
      %tr
        %td= image_tag category.image_url(:thumb)
        %td= category.title

        %td= link_to "Edit", edit_category_path(category)
        %td= link_to "Delete", category_path(category),
          data: { confirm: "Are you sure you want to delete #{category.title} category?" },
          method: :delete

app/views/categories/new.haml
%h1 Add New Category

= render 'form'

app/views/conversations/_conversation.html.haml
%li.list-group-item.clearfix
  = link_to conversation.subject, conversation_path(conversation)

app/views/conversations/index.html.haml
- page_header "Your Conversations"
%ul.list-group
  = render partial: 'conversations/conversation', collection: @conversations
= will_paginate

app/views/conversations/show.html.haml
- page_header "Conversation"
.panel.panel-default
  .panel-heading= @conversation.subject
  .panel-body
    .messages
      - @conversation.receipts_for(current_user).each do |receipt|
        - message = receipt.message
        = message.sender.name
        says at #{message.created_at.strftime("%-d %B %Y, %H:%M:%S")}
        \#{message.body}

app/views/layouts/_user_header.html.haml
%ul.nav.nav-pills.pull-right
  - if user_signed_in?
    %li= link_to "Sign out", destroy_user_session_path, :method => :delete
  - else
    %li= link_to "Sign in", new_user_session_path
    %li= link_to "Sign up", new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Thoughknacks
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .container
    - flash.each do |key, value|
      %div{:class => "alert alert-#{key}"}
        = value
    .page-header
      %p.alert= alert
      = yield

app/views/static_pages/home.html.haml
%body
  %nav.navbar.navbar-inverse
    .container
      %ul.nav.navbar-nav
        - if user_signed_in?
          %li.edit-profile= link_to 'Edit Profile', edit_user_registration_path
          %li= link_to "Sign out", destroy_user_session_path, :method => :delete
        - else
          %li= link_to 'Sign in', new_user_session_path
          %li= link_to 'Sign up', new_user_registration_path

app/views/users/shared/_links.html.haml
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name)
  %br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  %br/
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  %br/
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  %br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  %br/
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider)
    %br/

app/views/videos/_form.haml
=form_for @video, :html => {:multipart => true} do |f|

  %p Title:
  =f.text_field :title, placeholder: "Title"

  %p Description:
  =f.text_area :description, placeholder: "Description"

  %p Category:
  =f.select :category_id, options_for_select(Category.all.collect{ |x|[x.title, x.id]  })

  %p Thumbnail:
  =f.file_field :thumbnail, name: "video[thumbnail]"
  
  %p Video:
  =f.file_field :video_link, name: "video[video_link]"

  %p 
    =f.submit 

app/views/videos/_video.haml
.col-md-4.portfolio-item
  %img.img-responsive
    = image_tag video.thumbnail_url(:thumb)
  %h3
    = link_to video_path(video) do
      = video.title
  %p 
    = video.description

    = link_to 'Edit', edit_video_path(video)
  
    = link_to "Delete", video_path(video),
          data: { confirm: "Are you sure you want to delete #{video.title}" },
          method: :delete

app/views/videos/_videos.haml
.container
  .row
    .col-lg-12
      %h1.page-header
        Ruby on Rails

  .row
    - @videos.each do |video|
      =render 'video', video: video

app/views/videos/edit.haml
%h1 Edit Video

= render "form"

app/views/videos/index.haml
%h1 Video List

#flash_messages= flash_messages(:close, :fade)
= link_to "Upload New Video", new_video_path

=render 'videos', videos: @videos

app/views/videos/new.haml
%h1 Upload Videos
- if @video.errors.any?
  %h3
    = pluralize(@video.errors.count, "error")
    prohibited this video from being uploaded:
  %ul
    - @video.errors.full_messages.each do |msg|
      %li= msg

= render "form"

app/views/videos/show.haml
%h1 View Videos

#flash_messages= flash_messages(:close, :fade)

=link_to 'Upload New Videos', new_video_path

%p Title: 
=@video.title

%p Video:
/ =video_tag("#{@video.video_link_url()}",controls: true, type: "video")
=video_tag(@video.video_link_url(:mp4), controls: true)

%p Body:
=@video.description

%p Tag:
=@video.category.title